apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  namespace: default
  labels:
    app: {{name}}
spec:
  type: NodePort
  ports:
  - port: {{port}}
    name: amqp
  selector:
    app: {{name}}